<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<section class="hero container"><div class="row align-items-center gy-4">
<div class="col-lg-6 hero-copy"><p class="eyebrow"><span class="tiny-diamond" aria-hidden="true"></span> Batik pilihan dari Ponorogo</p><h1>Warisan dalam<br>setiap <em>corak.</em></h1><p class="hero-description">Sentuhan tradisi, untuk cerita masa kini. Temukan batik pilihan yang menemani keseharian hingga momen istimewa Anda.</p><div class="d-flex flex-wrap gap-3"><a class="btn btn-primary" href="<?= site_url('katalog') ?>">Lihat Katalog <span aria-hidden="true">↗</span></a><a class="btn btn-outline-primary" href="<?= site_url('tentang') ?>">Tentang Kami</a></div><div class="hero-note"><span class="note-line" aria-hidden="true"></span><span>Kain, kemeja, dan blus.<br>Satu ruang untuk mencintai batik.</span></div></div>
<div class="col-lg-6"><figure class="hero-art"><img src="<?= base_url('assets/images/hero.svg') ?>" width="700" height="740" alt="Ilustrasi kain batik warna sogan dan terracotta yang digantung pada batang kayu" fetchpriority="high"><figcaption><span>CORAK PILIHAN</span><strong>Berakar pada tradisi.</strong><span class="art-caption">Ilustrasi koleksi batik</span></figcaption><span class="art-seal" aria-hidden="true">BATIK<br>◆<br>PUSAKA</span></figure></div>
</div></section>
<div class="values-strip"><div class="container"><span><span aria-hidden="true">◇</span> Ragam corak, satu warisan</span><span><span aria-hidden="true">◇</span> Pilihan untuk keseharian</span><span><span aria-hidden="true">◇</span> Tanya langsung via WhatsApp</span></div></div>
<section class="section-space container"><div class="section-heading"><div><p class="eyebrow">TEMUKAN FAVORIT ANDA</p><h2>Pilihan dari koleksi kami</h2></div><a class="text-link" href="<?= site_url('katalog') ?>">Lihat semua koleksi <span aria-hidden="true">↗</span></a></div><div class="row g-4">
<?php foreach ($products as $product): ?><div class="col-12 col-sm-6 col-lg-3"><?= view('partials/product_card', ['product' => $product]) ?></div><?php endforeach ?>
<?php if (! $products): ?><p>Koleksi sedang disiapkan. Silakan kunjungi kembali.</p><?php endif ?>
</div></section>
<section class="container pb-5"><div class="story-panel"><div><p class="eyebrow">LEBIH DEKAT DENGAN BATIK</p><h2>Bukan sekadar busana.<br>Bagian dari cerita kita.</h2></div><div><p>Kami menghadirkan ruang sederhana untuk menemukan batik yang sesuai dengan selera Anda. Jelajahi coraknya, kenali produknya, lalu berbincang langsung dengan kami.</p><a class="text-link" href="<?= site_url('tentang') ?>">Kenali Batik Pusaka <span aria-hidden="true">↗</span></a></div></div></section>
<?= $this->endSection() ?>
